version: '3'
services:
  app:
    build:
      context: .
      dockerfile: docker/express/Dockerfile
    container_name: prologix_express
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: ${DATABASE_URL}
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - prologix

  db:
    image: postgres:13
    container_name: prologix_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - prologix

volumes:
  postgres_data:

networks:
  prologix:
